services:
  - type: web
    name: neutrikenya
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn neutrikenya.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 