# Generated by Django 5.2.1 on 2025-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_delivery_instructions_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_products',
            field=models.ManyToManyField(blank=True, related_name='compatible_with', to='store.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='key_ingredients',
            field=models.TextField(blank=True, help_text='Main active ingredients and their benefits'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, help_text='Recommended skin types', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.ingredient'),
        ),
    ]
