# Generated by Django 5.2.1 on 2025-06-09 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_ingredient_options_remove_ingredient_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bundle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundled_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundled_in', to='store.product')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_bundles', to='store.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('main_product', 'bundled_product')},
            },
        ),
        migrations.DeleteModel(
            name='ComplementaryProduct',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='ProductIngredient',
        ),
    ]
