# Generated by Django 5.2.1 on 2025-06-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_productingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductBundle',
        ),
    ]
